/* Auto-generated by scripts/build-layouts.ts. Do not edit manually. */

import compiled from "./compiled.json";
import { applyTemplateTokensToRecord } from "@/lib/templateTokens";

type CompiledLayoutsJson = {
  compiledLayoutHtmlBySlug: Record<string, string>;
  layoutCompileWarningsBySlug: Record<string, string[]>;
};

const compiledOutput = compiled as CompiledLayoutsJson;

export const compiledLayoutHtmlBySlug =
  applyTemplateTokensToRecord(compiledOutput.compiledLayoutHtmlBySlug);
export const layoutCompileWarningsBySlug =
  compiledOutput.layoutCompileWarningsBySlug;
