/* Auto-generated by scripts/build-layout-addons.ts. Do not edit manually. */

export type ReadyLayoutAddon = {
  slug: string;
  title: string;
  description: string;
  sourceFolder: string;
  sourceFile: string;
  previewImageUrl: string | null;
  mjmlPath: string;
  sourceBlocks: string[];
  packComponentSlugs: string[];
};

export const READY_LAYOUT_ADDON_SOURCE_FOLDER_COUNT = 70;
export const READY_LAYOUT_ADDON_SOURCE_TEMPLATE_COUNT = 70;
export const READY_LAYOUT_ADDON_DUPLICATE_TEMPLATE_COUNT = 0;

export const readyLayoutAddons = [
  {
    "slug": "accredititedstaff24",
    "title": "AccredititedStaff24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "AccredititedStaff24",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/accredititedstaff24.png",
    "mjmlPath": "/private/layout-addons/mjml/accredititedstaff24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "aftercare-1-0522",
    "title": "Aftercare 1 0522",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "aftercare-1-0522",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/aftercare-1-0522.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-overlay-modern",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "aftercare-2-0522",
    "title": "Aftercare 2 0522",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "aftercare-2-0522",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/aftercare-2-0522.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-overlay-modern",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "aftercare-3-0522",
    "title": "Aftercare 3 0522",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "aftercare-3-0522",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/aftercare-3-0522.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-overlay-modern",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "aftercare-feb-22",
    "title": "Aftercare Feb 22",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Aftercare-feb-22",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/aftercare-feb-22.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "logo-grid-trust-strip",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "aftercare-feb-22-1",
    "title": "Aftercare Feb 22 (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Aftercare-feb-22 (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/aftercare-feb-22-1.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "aftercare-jan-22",
    "title": "Aftercare Jan 22",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Aftercare-jan-22",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/aftercare-jan-22.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "logo-grid-trust-strip",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "algoriq",
    "title": "AlgorIQ",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "AlgorIQ",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/algoriq.png",
    "mjmlPath": "/private/layout-addons/mjml/algoriq.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "blogarticles24",
    "title": "Blogarticles24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "blogarticles24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/blogarticles24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "charityemail",
    "title": "Charityemail",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Charityemail",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/charityemail.png",
    "mjmlPath": "/private/layout-addons/mjml/charityemail.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "christmas",
    "title": "Christmas",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Christmas",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/christmas.png",
    "mjmlPath": "/private/layout-addons/mjml/christmas.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "christmas24",
    "title": "Christmas24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "christmas24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/christmas24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "company-birthday24",
    "title": "Company Birthday24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "company-birthday24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/company-birthday24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "company-birthday24-2-1",
    "title": "Company Birthday24 2.1",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "company-birthday24-2.1",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/company-birthday24-2-1.png",
    "mjmlPath": "/private/layout-addons/mjml/company-birthday24-2-1.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "contractor-vs-team",
    "title": "Contractor Vs Team",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "contractor-vs-team",
    "sourceFile": "contractor-vs-team.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/contractor-vs-team.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "diwali24",
    "title": "Diwali24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Diwali24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/diwali24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-dual-col",
    "title": "E3 Dual Col",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-dual-col",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-dual-col.mjml",
    "sourceBlocks": [
      "single image left reverse"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "accent-cta-button",
      "single-image-left",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-lead-1",
    "title": "E3 Lead 1",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "E3-lead-1",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/e3-lead-1.png",
    "mjmlPath": "/private/layout-addons/mjml/e3-lead-1.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-multi",
    "title": "E3 Multi",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-multi",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-multi.mjml",
    "sourceBlocks": [
      "hero image left",
      "Primary Call to Action",
      "hero image right reverse"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-multi-1",
    "title": "E3 Multi (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-multi (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-multi-1.mjml",
    "sourceBlocks": [
      "hero image left",
      "Primary Call to Action",
      "hero image right reverse"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-multi-1-1",
    "title": "E3 Multi (1) (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-multi (1) (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-multi-1-1.mjml",
    "sourceBlocks": [
      "dual image",
      "Centred CTA",
      "triple image"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-multi-1-1-1",
    "title": "E3 Multi (1) (1) (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-multi (1) (1) (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-multi-1-1-1.mjml",
    "sourceBlocks": [
      "Primary Call to Action",
      "review centred",
      "app download superlight"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "accent-cta-button",
      "testimonial-quote",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-newdesign",
    "title": "E3 Newdesign",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-newdesign",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-newdesign.mjml",
    "sourceBlocks": [
      "hero image left",
      "Primary Call to Action"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-overlay-modern",
      "hero-image-left",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-single0col",
    "title": "E3 Single0col",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-single0col",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-single0col.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-single0col-1",
    "title": "E3 Single0col (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-single0col (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-single0col-1.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-single0col-1-1",
    "title": "E3 Single0col (1) (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-single0col (1) (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-single0col-1-1.mjml",
    "sourceBlocks": [
      "hero image left",
      "Primary Call to Action"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-single0col-1-1-1",
    "title": "E3 Single0col (1) (1) (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-single0col (1) (1) (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-single0col-1-1-1.mjml",
    "sourceBlocks": [
      "hero image left",
      "Primary Call to Action",
      "hero image right reverse"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-single0col-1-1-1-1",
    "title": "E3 Single0col (1) (1) (1) (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-single0col (1) (1) (1) (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-single0col-1-1-1-1.mjml",
    "sourceBlocks": [
      "dual image"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-single0col-1-1-1-1-1",
    "title": "E3 Single0col (1) (1) (1) (1) (1)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-single0col (1) (1) (1) (1) (1)",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/e3-single0col-1-1-1-1-1.png",
    "mjmlPath": "/private/layout-addons/mjml/e3-single0col-1-1-1-1-1.mjml",
    "sourceBlocks": [
      "Primary Call to Action",
      "single image left reverse",
      "single image right"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "logo-grid-trust-strip",
      "accent-cta-button",
      "single-image-left",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-single0col-1-1-2",
    "title": "E3 Single0col (1) (1) (2)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-single0col (1) (1) (2)",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3-single0col-1-1-2.mjml",
    "sourceBlocks": [
      "hero image left",
      "Primary Call to Action"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3-single0col-2",
    "title": "E3 Single0col (2)",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3-single0col (2)",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/e3-single0col-2.png",
    "mjmlPath": "/private/layout-addons/mjml/e3-single0col-2.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3leads24",
    "title": "E3Leads24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3Leads24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3leads24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "e3leads24-3-1",
    "title": "E3Leads24 3.1",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "e3Leads24-3.1",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/e3leads24-3-1.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "erp-hero",
    "title": "Erp Hero",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "erp-hero",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/erp-hero.png",
    "mjmlPath": "/private/layout-addons/mjml/erp-hero.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "header-brand-row"
    ]
  },
  {
    "slug": "erp-hero-left",
    "title": "Erp Hero Left",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "erp-hero-left",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/erp-hero-left.png",
    "mjmlPath": "/private/layout-addons/mjml/erp-hero-left.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "header-brand-row"
    ]
  },
  {
    "slug": "fireworks",
    "title": "Fireworks",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Fireworks",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/fireworks.png",
    "mjmlPath": "/private/layout-addons/mjml/fireworks.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "flight",
    "title": "Flight",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "flight",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/flight.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "generic-1col",
    "title": "Generic 1col",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Generic-1col",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/generic-1col.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "generic-2col",
    "title": "Generic 2col",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Generic-2col",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/generic-2col.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "generic-2col-hf",
    "title": "Generic 2col Hf",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Generic-2col-hf",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/generic-2col-hf.png",
    "mjmlPath": "/private/layout-addons/mjml/generic-2col-hf.mjml",
    "sourceBlocks": [
      "header-e3-center.mjml",
      "footer-24-white.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "generic-blognewsletter",
    "title": "Generic Blognewsletter",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Generic-blognewsletter",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/generic-blognewsletter.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "dual-image-feature-grid",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "generic-event",
    "title": "Generic Event",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Generic-event",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/generic-event.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "generic-event-black-and-gold",
    "title": "Generic Event Black&Gold",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Generic-event-black&gold",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/generic-event-black-and-gold.mjml",
    "sourceBlocks": [
      "header-black-e3.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "generic-mixcol",
    "title": "Generic Mixcol",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Generic-mixcol",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/generic-mixcol.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "guy-fawkes24",
    "title": "Guy Fawkes24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Guy Fawkes24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/guy-fawkes24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "halloween",
    "title": "Halloween",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Halloween",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/halloween.png",
    "mjmlPath": "/private/layout-addons/mjml/halloween.mjml",
    "sourceBlocks": [
      "header-black-e3.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "halloween24",
    "title": "Halloween24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Halloween24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/halloween24.mjml",
    "sourceBlocks": [
      "header-black-e3.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "handle-truth-0624",
    "title": "Handle Truth 0624",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Handle-truth-0624",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/handle-truth-0624.png",
    "mjmlPath": "/private/layout-addons/mjml/handle-truth-0624.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "investing-in-a-netsuite-partner-0624",
    "title": "Investing In A Netsuite Partner 0624",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "investing-in-a-netsuite-partner-0624",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/investing-in-a-netsuite-partner-0624.png",
    "mjmlPath": "/private/layout-addons/mjml/investing-in-a-netsuite-partner-0624.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "kingsbirthday24",
    "title": "Kingsbirthday24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "kingsbirthday24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/kingsbirthday24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "magic",
    "title": "Magic",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "magic",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/magic.png",
    "mjmlPath": "/private/layout-addons/mjml/magic.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "netsuite-ai-reporting",
    "title": "NetSuite AI Reporting",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "NetSuite-AI-Reporting",
    "sourceFile": "NetSuite-AI-Reporting.mjml",
    "previewImageUrl": "/layout-addons-previews/netsuite-ai-reporting.png",
    "mjmlPath": "/private/layout-addons/mjml/netsuite-ai-reporting.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "netsuite-support-em1",
    "title": "Netsuite Support Em1",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Netsuite-support-em1",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/netsuite-support-em1.png",
    "mjmlPath": "/private/layout-addons/mjml/netsuite-support-em1.mjml",
    "sourceBlocks": [
      "edge image left",
      "single image right reverse",
      "single image left"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "logo-grid-trust-strip",
      "accent-cta-button",
      "single-image-left",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "netsuite-support-em1v2",
    "title": "Netsuite Support Em1v2",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Netsuite-support-em1v2",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/netsuite-support-em1v2.png",
    "mjmlPath": "/private/layout-addons/mjml/netsuite-support-em1v2.mjml",
    "sourceBlocks": [
      "edge image left",
      "single image right reverse",
      "single image left"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "hero-image-left",
      "dual-image-feature-grid",
      "logo-grid-trust-strip",
      "accent-cta-button",
      "single-image-left",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "new-footer-22",
    "title": "New Footer 22",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "new-footer-22",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/new-footer-22.mjml",
    "sourceBlocks": [],
    "packComponentSlugs": [
      "header-brand-row",
      "logo-grid-trust-strip",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "newyears24",
    "title": "Newyears24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "newyears24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/newyears24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "poor-netsuite-0624",
    "title": "Poor NetSuite 0624",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Poor-NetSuite-0624",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/poor-netsuite-0624.png",
    "mjmlPath": "/private/layout-addons/mjml/poor-netsuite-0624.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "remeberance24",
    "title": "Remeberance24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Remeberance24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/remeberance24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "rockets",
    "title": "Rockets",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "rockets",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/rockets.png",
    "mjmlPath": "/private/layout-addons/mjml/rockets.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "rockets-followup",
    "title": "Rockets Followup",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "rockets-followup",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/rockets-followup.png",
    "mjmlPath": "/private/layout-addons/mjml/rockets-followup.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "service-disruption-1406",
    "title": "Service Disruption 1406",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Service-disruption-1406",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/service-disruption-1406.png",
    "mjmlPath": "/private/layout-addons/mjml/service-disruption-1406.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "single-image-left",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "space",
    "title": "Space",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "space",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/space.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "star-wars-day24",
    "title": "Star Wars Day24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Star Wars Day24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/star-wars-day24.mjml",
    "sourceBlocks": [
      "header-black-e3.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "suiteworld24",
    "title": "SuiteWorld24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "SuiteWorld24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/suiteworld24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "the-hidden-costs-of-relyiong-on-spreadsheets",
    "title": "The Hidden Costs Of Relyiong On Spreadsheets",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "The hidden costs of relyiong on spreadsheets",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/the-hidden-costs-of-relyiong-on-spreadsheets.png",
    "mjmlPath": "/private/layout-addons/mjml/the-hidden-costs-of-relyiong-on-spreadsheets.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "train",
    "title": "Train",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "train",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/train.png",
    "mjmlPath": "/private/layout-addons/mjml/train.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "valentines24",
    "title": "Valentines24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "valentines24",
    "sourceFile": "index.mjml",
    "previewImageUrl": null,
    "mjmlPath": "/private/layout-addons/mjml/valentines24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "visuallinkedin24",
    "title": "VisualLinkedIn24",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "visualLinkedIn24",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/visuallinkedin24.png",
    "mjmlPath": "/private/layout-addons/mjml/visuallinkedin24.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "accent-cta-button",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "whatisyournetscore-mini",
    "title": "Whatisyournetscore Mini",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Whatisyournetscore-mini",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/whatisyournetscore-mini.png",
    "mjmlPath": "/private/layout-addons/mjml/whatisyournetscore-mini.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "footer-contact-compliance"
    ]
  },
  {
    "slug": "whatisyournetscore-mini-v2",
    "title": "Whatisyournetscore Mini V2",
    "description": "Debranded ready-to-send MJML layout template. Swap copy, imagery, links, and brand tokens.",
    "sourceFolder": "Whatisyournetscore-mini v2",
    "sourceFile": "index.mjml",
    "previewImageUrl": "/layout-addons-previews/whatisyournetscore-mini-v2.png",
    "mjmlPath": "/private/layout-addons/mjml/whatisyournetscore-mini-v2.mjml",
    "sourceBlocks": [
      "header.mjml",
      "footer.mjml"
    ],
    "packComponentSlugs": [
      "header-brand-row",
      "footer-contact-compliance"
    ]
  }
] as const satisfies readonly ReadyLayoutAddon[];

export const READY_LAYOUT_ADDON_COUNT = readyLayoutAddons.length;

function assertNoDuplicateReadyLayoutSlugs(addons: readonly ReadyLayoutAddon[]): void {
  const seen = new Set<string>();

  for (const addon of addons) {
    if (seen.has(addon.slug)) {
      throw new Error(`[layout-addons] Duplicate slug found: "${addon.slug}".`);
    }
    seen.add(addon.slug);
  }
}

const KNOWN_PACK_COMPONENT_SLUGS = ["header-brand-row","hero-overlay-modern","hero-image-left","dual-image-feature-grid","quad-image-showcase","logo-grid-trust-strip","accent-cta-button","single-image-left","testimonial-quote","footer-contact-compliance"] as const;

function assertKnownPackComponentSlugs(addons: readonly ReadyLayoutAddon[]): void {
  const known = new Set<string>(KNOWN_PACK_COMPONENT_SLUGS);

  for (const addon of addons) {
    for (const componentSlug of addon.packComponentSlugs) {
      if (!known.has(componentSlug)) {
        throw new Error(
          `[layout-addons] Unknown pack component slug "${componentSlug}" in "${addon.slug}".`,
        );
      }
    }
  }
}

function assertSourceBlocksShape(addons: readonly ReadyLayoutAddon[]): void {
  for (const addon of addons) {
    if (!Array.isArray(addon.sourceBlocks)) {
      throw new Error(
        `[layout-addons] sourceBlocks must be an array for "${addon.slug}".`,
      );
    }
  }
}

assertNoDuplicateReadyLayoutSlugs(readyLayoutAddons);
assertKnownPackComponentSlugs(readyLayoutAddons);
assertSourceBlocksShape(readyLayoutAddons);
