/* Auto-generated by scripts/build-examples.ts. Do not edit manually. */

import compiled from "./compiled.json";
import { applyTemplateTokensToRecord } from "@/lib/templateTokens";

export const compiledExamplesBySlug: Record<string, string> =
  applyTemplateTokensToRecord(compiled as Record<string, string>);
