import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { emailComponents } from "../src/data/email-components";
import { compileMjml } from "../src/lib/mjml/compile";

const outputPath = path.join(
  process.cwd(),
  "src",
  "data",
  "email-components",
  "compiled.ts",
);
const outputJsonPath = path.join(
  process.cwd(),
  "src",
  "data",
  "email-components",
  "compiled.json",
);
const publicDir = path.join(process.cwd(), "public");

async function assertPreviewAsset(previewImageUrl: string, slug: string): Promise<void> {
  const trimmed = previewImageUrl.trim();
  if (!trimmed.startsWith("/")) {
    throw new Error(
      `Component "${slug}" has an invalid previewImageUrl "${previewImageUrl}". Expected a public absolute path starting with /.`,
    );
  }

  const previewPath = path.join(publicDir, trimmed.slice(1));
  await fs.access(previewPath);
}

async function getPreviewAssetHash(previewImageUrl: string): Promise<string> {
  const previewPath = path.join(publicDir, previewImageUrl.trim().slice(1));
  const previewBuffer = await fs.readFile(previewPath);
  return createHash("sha256").update(previewBuffer).digest("hex");
}

async function buildCompiledComponents() {
  const compiledComponentsBySlug: Record<string, string> = {};
  const seenPreviewImageUrls = new Map<string, string>();
  const seenPreviewHashes = new Map<string, string>();

  for (const component of emailComponents) {
    try {
      const existingPreviewOwner = seenPreviewImageUrls.get(component.previewImageUrl);
      if (existingPreviewOwner) {
        throw new Error(
          `Duplicate previewImageUrl "${component.previewImageUrl}" is assigned to both "${existingPreviewOwner}" and "${component.slug}".`,
        );
      }

      seenPreviewImageUrls.set(component.previewImageUrl, component.slug);
      await assertPreviewAsset(component.previewImageUrl, component.slug);
      const previewHash = await getPreviewAssetHash(component.previewImageUrl);
      const existingPreviewHashOwner = seenPreviewHashes.get(previewHash);
      if (existingPreviewHashOwner) {
        throw new Error(
          `Preview asset "${component.previewImageUrl}" is visually identical to the preview already used by "${existingPreviewHashOwner}". Generate a distinct preview before shipping.`,
        );
      }

      seenPreviewHashes.set(previewHash, component.slug);
      compiledComponentsBySlug[component.slug] = await compileMjml(component.mjmlSource);
    } catch (error) {
      const reason = error instanceof Error ? error.message : "Unknown error";
      throw new Error(
        `Failed to compile MJML for "${component.slug}" (${component.title}): ${reason}`,
      );
    }
  }

  const output = `/* Auto-generated by scripts/build-components.ts. Do not edit manually. */

import compiled from "./compiled.json";
import { applyTemplateTokensToRecord } from "@/lib/templateTokens";

export const compiledComponentsBySlug: Record<string, string> =
  applyTemplateTokensToRecord(compiled as Record<string, string>);
`;

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(
    outputJsonPath,
    `${JSON.stringify(compiledComponentsBySlug, null, 2)}\n`,
    "utf8",
  );
  await fs.writeFile(outputPath, output, "utf8");

  process.stdout.write(
    `Compiled ${Object.keys(compiledComponentsBySlug).length} MJML component(s) to ${outputPath} and ${outputJsonPath}\n`,
  );
}

buildCompiledComponents().catch((error) => {
  const message = error instanceof Error ? error.message : "Unknown build failure";
  process.stderr.write(`${message}\n`);
  process.exit(1);
});
