import { promises as fs } from "node:fs";
import path from "node:path";
import { emailExamples } from "../src/data/email-examples";
import { compileMjml } from "../src/lib/mjml/compile";

const outputPath = path.join(
  process.cwd(),
  "src",
  "data",
  "email-examples",
  "compiled.ts",
);
const outputJsonPath = path.join(
  process.cwd(),
  "src",
  "data",
  "email-examples",
  "compiled.json",
);

async function buildCompiledExamples(): Promise<void> {
  const compiledExamplesBySlug: Record<string, string> = {};

  for (const example of emailExamples) {
    try {
      compiledExamplesBySlug[example.slug] = await compileMjml(example.mjmlSource);
    } catch (error) {
      const reason = error instanceof Error ? error.message : "Unknown error";
      throw new Error(
        `Failed to compile example MJML for \"${example.slug}\" (${example.title}): ${reason}`,
      );
    }
  }

  const moduleOutput = `/* Auto-generated by scripts/build-examples.ts. Do not edit manually. */

import compiled from "./compiled.json";
import { applyTemplateTokensToRecord } from "@/lib/templateTokens";

export const compiledExamplesBySlug: Record<string, string> =
  applyTemplateTokensToRecord(compiled as Record<string, string>);
`;

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(
    outputJsonPath,
    `${JSON.stringify(compiledExamplesBySlug, null, 2)}\n`,
    "utf8",
  );
  await fs.writeFile(outputPath, moduleOutput, "utf8");

  process.stdout.write(
    `Compiled ${Object.keys(compiledExamplesBySlug).length} MJML example(s) to ${outputPath} and ${outputJsonPath}\n`,
  );
}

buildCompiledExamples().catch((error) => {
  const message = error instanceof Error ? error.message : "Unknown build failure";
  process.stderr.write(`${message}\n`);
  process.exit(1);
});
