import { promises as fs } from "node:fs";
import path from "node:path";
import { emailLayouts } from "../src/data/email-layouts";
import { compileMjml } from "../src/lib/mjml/compile";

const outputPath = path.join(
  process.cwd(),
  "src",
  "data",
  "email-layouts",
  "compiled.ts",
);
const outputJsonPath = path.join(
  process.cwd(),
  "src",
  "data",
  "email-layouts",
  "compiled.json",
);
const publicDir = path.join(process.cwd(), "public");

type CompiledLayoutsOutput = {
  compiledLayoutHtmlBySlug: Record<string, string>;
  layoutCompileWarningsBySlug: Record<string, string[]>;
};

async function assertPreviewAsset(previewImageUrl: string, slug: string): Promise<void> {
  const trimmed = previewImageUrl.trim();
  if (!trimmed.startsWith("/")) {
    throw new Error(
      `Layout "${slug}" has an invalid previewImageUrl "${previewImageUrl}". Expected a public absolute path starting with /.`,
    );
  }

  const previewPath = path.join(publicDir, trimmed.slice(1));
  await fs.access(previewPath);
}

async function buildCompiledLayouts() {
  const output: CompiledLayoutsOutput = {
    compiledLayoutHtmlBySlug: {},
    layoutCompileWarningsBySlug: {},
  };

  for (const layout of emailLayouts) {
    try {
      await assertPreviewAsset(layout.previewImageUrl, layout.slug);
      output.compiledLayoutHtmlBySlug[layout.slug] = await compileMjml(layout.mjmlSource);
      output.layoutCompileWarningsBySlug[layout.slug] = [];
    } catch (error) {
      const reason = error instanceof Error ? error.message : "Unknown error";
      throw new Error(
        `Failed to compile layout MJML for "${layout.slug}" (${layout.title}): ${reason}`,
      );
    }
  }

  const moduleOutput = `/* Auto-generated by scripts/build-layouts.ts. Do not edit manually. */

import compiled from "./compiled.json";
import { applyTemplateTokensToRecord } from "@/lib/templateTokens";

type CompiledLayoutsJson = {
  compiledLayoutHtmlBySlug: Record<string, string>;
  layoutCompileWarningsBySlug: Record<string, string[]>;
};

const compiledOutput = compiled as CompiledLayoutsJson;

export const compiledLayoutHtmlBySlug =
  applyTemplateTokensToRecord(compiledOutput.compiledLayoutHtmlBySlug);
export const layoutCompileWarningsBySlug =
  compiledOutput.layoutCompileWarningsBySlug;
`;

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputJsonPath, `${JSON.stringify(output, null, 2)}\n`, "utf8");
  await fs.writeFile(outputPath, moduleOutput, "utf8");

  process.stdout.write(
    `Compiled ${Object.keys(output.compiledLayoutHtmlBySlug).length} MJML layout(s) to ${outputPath} and ${outputJsonPath}\n`,
  );
}

buildCompiledLayouts().catch((error) => {
  const message = error instanceof Error ? error.message : "Unknown build failure";
  process.stderr.write(`${message}\n`);
  process.exit(1);
});
